language: python
python:   
  - "3.7"	# current default Python on Travis CI is 3.6

before_script:
  - wget https://github.com/tylunel/pvlib-python.tar.gz -O /tmp/pvlib.tar.gz
  - tar -xvf /tmp/pvlib.tar.gz
  - export PATH=$PATH:$PWD/pvlib/bin/

# command to install dependencies
install:
 - pip install -r requirements-test.txt


# command to run tests
script:
  - pytest