name: CI general checks

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  build:

    # Decide which environnement the package will be tested on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, vs2017-win2016]

    steps:
    # make a copy of concerned repository's code, for being used later. '@v1' get the stable version. Not clear why I still need to install pvpumpingsystem later..
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: codecov  (Does not seems to actually work for now)
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required

    - name: Install dependencies
      run: |  # The pipe (|) is a tool allowing us to write multiple lines that execute independently without having to use multiple run commands or multiple jobs.
        python -m pip install --upgrade pip
        # pip install git+https://github.com/tylunel/pvlib-python@all_changes#egg=pvlib  # It is possible to specify the branch we want to download with @<branch>
        pip install git+https://github.com/pvlib/pvlib-python#egg=pvlib  # still useful because last changes are not in the last release that can be found on pip
        pip install git+https://github.com/tylunel/pvpumpingsystem#egg=pvpumpingsystem
        pip install matplotlib sklearn tqdm fluids numpy_financial

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --ignore=E226, E231, E241, E265, E266, F401, E741
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

	# exit-zero treats all errors as warnings. 
	# max-line-length=127: editor is 127 chars wide

    - name: Test with pytest
      run: |
        pip install pytest
        pytest
